ALTER TABLE notifications ADD COLUMN title TEXT;
ALTER TABLE agent_skills ADD COLUMN updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ai_sessions ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
